# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :CI do
      run_tests(project: "SwiftStarterProject.xcodeproj",
      devices: ["iPhone 6s"],
      scheme: "SwiftStarterProject")
  end

  lane :CD do |values|

    gym(scheme: 'SwiftStarterProject', project: "SwiftStarterProject.xcodeproj", clean: true, silent: true, include_bitcode: false, export_method: 'ad-hoc')

    emails = values[:test_email] ? values[:test_email] : ['durgesh.pandey@globant.com'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here
end
